services:
  - type: web
    name: pdf-to-docx
    env: python
    plan: free
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r requirements.txt
    startCommand: cd django_site && gunicorn django_site.wsgi:application --bind 0.0.0.0:$PORT --log-file -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
      - key: DJANGO_SETTINGS_MODULE
        value: django_site.settings
